countries_and_flags = {
    "United States": "🇺🇸",
    "Canada": "🇨🇦",
    "United Kingdom": "🇬🇧",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Italy": "🇮🇹",
    "Spain": "🇪🇸",
    "Japan": "🇯🇵",
    "China": "🇨🇳",
    "India": "🇮🇳",
    "Brazil": "🇧🇷",
    "Australia": "🇦🇺",
    "South Korea": "🇰🇷",
    "Mexico": "🇲🇽",
    "Russia": "🇷🇺",
    "South Africa": "🇿🇦",
    "Nigeria": "🇳🇬",
    "Argentina": "🇦🇷",
    "Egypt": "🇪🇬",
    "Saudi Arabia": "🇸🇦",
    "Turkey": "🇹🇷",
    "Sweden": "🇸🇪",
    "Norway": "🇳🇴",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Switzerland": "🇨🇭",
    "Austria": "🇦🇹",
    "Greece": "🇬🇷",
    "Portugal": "🇵🇹",
    "Poland": "🇵🇱",
    "Czech Republic": "🇨🇿",
    "Hungary": "🇭🇺",
    "Israel": "🇮🇱",
    "New Zealand": "🇳🇿",
    "Singapore": "🇸🇬",
    "Malaysia": "🇲🇾",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Indonesia": "🇮🇩",
    "Philippines": "🇵🇭",
    "Pakistan": "🇵🇰",
    "Bangladesh": "🇧🇩",
    "Sri Lanka": "🇱🇰",
    "Nepal": "🇳🇵",
    "Bhutan": "🇧🇹",
    "Maldives": "🇲🇻",
    "Afghanistan": "🇦🇫",
    "Iraq": "🇮🇶",
    "Iran": "🇮🇷",
    "Syria": "🇸🇾",
    "Jordan": "🇯🇴",
    "Lebanon": "🇱🇧",
    "Palestine": "🇵🇸",
    "Oman": "🇴🇲",
    "Yemen": "🇾🇪",
    "Qatar": "🇶🇦",
    "United Arab Emirates": "🇦🇪",
    "Kuwait": "🇰🇼",
    "Bahrain": "🇧🇭",
    "Morocco": "🇲🇦",
    "Algeria": "🇩🇿",
    "Tunisia": "🇹🇳",
    "Libya": "🇱🇾",
    "Sudan": "🇸🇩",
    "Ethiopia": "🇪🇹",
    "Kenya": "🇰🇪",
    "Uganda": "🇺🇬",
    "Tanzania": "🇹🇿",
    "Zimbabwe": "🇿🇼",
    "Zambia": "🇿🇲",
    "Mozambique": "🇲🇿",
    "Botswana": "🇧🇼",
    "Namibia": "🇳🇦",
    "Angola": "🇦🇴",
    "Democratic Republic of the Congo": "🇨🇩",
    "Ivory Coast": "🇨🇮",
    "Senegal": "🇸🇳",
    "Ghana": "🇬🇭",
    "Cameroon": "🇨🇲",
    "Uganda": "🇺🇬",
    "Madagascar": "🇲🇬",
    "Mauritius": "🇲🇺",
    "Seychelles": "🇸🇨",
    "Malawi": "🇲🇼",
    "Rwanda": "🇷🇼",
    "Burundi": "🇧🇮",
    "Somalia": "🇸🇴",
    "Djibouti": "🇩🇯",
    "Eritrea": "🇪🇷",
    "Chad": "🇹🇩",
    "Central African Republic": "🇨🇫",
    "Niger": "🇳🇪",
    "Mali": "🇲🇱",
    "Burkina Faso": "🇧🇫",
    "Liberia": "🇱🇷",
    "Sierra Leone": "🇸🇱",
    "Guinea": "🇬🇳",
    "Guinea-Bissau": "🇬🇼",
    "Gambia": "🇬🇲",
    "Benin": "🇧🇯",
    "Togo": "🇹🇬",
    "Mauritania": "🇲🇷",
    "Western Sahara": "🇪🇭",
    "Cape Verde": "🇨🇻",
    "Sao Tome and Principe": "🇸🇹",
    "Eswatini": "🇸🇿",
    "Lesotho": "🇱🇸",
    "Papua New Guinea": "🇵🇬",
    "Fiji": "🇫🇯",
    "Solomon Islands": "🇸🇧",
    "Vanuatu": "🇻🇺",
    "Samoa": "🇼🇸",
    "Tonga": "🇹🇴",
    "Kiribati": "🇰🇮",
    "Tuvalu": "🇹🇻",
    "Nauru": "🇳🇷",
    "Palau": "🇵🇼",
    "Marshall Islands": "🇲🇭",
    "Micronesia": "🇫🇲"
}

country_choices = [(key, key + ' ' + value) for key, value in countries_and_flags.items()]